# Generated by Django 3.0.3 on 2020-08-20 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('industry', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='YearReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earn_per_share', models.CharField(max_length=16)),
                ('income', models.CharField(max_length=16)),
                ('income_yoy', models.CharField(max_length=16)),
                ('income_qoq', models.CharField(max_length=16)),
                ('net_profits', models.CharField(max_length=16)),
                ('net_profits_yoy', models.CharField(max_length=16)),
                ('net_profits_qoq', models.CharField(max_length=16)),
                ('net_asset_per_share', models.CharField(max_length=16)),
                ('roe', models.CharField(max_length=16)),
                ('cash_per_share', models.CharField(max_length=16)),
                ('gross_rate', models.CharField(max_length=16)),
                ('distribution', models.CharField(max_length=16)),
                ('publish_date', models.CharField(max_length=16)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shares.Share')),
            ],
        ),
    ]
